---
- name: Preparing sshd_config for direct root key-pair authorization.
  hosts: all_production_hosts
  tasks:
  - name: Make a copy of /etc/ssh/sshd_config .
    copy:
      src: /etc/ssh/sshd_config
      dest: /etc/ssh/sshd_config.backup
      remote_src: yes

  - name: Copy a template ssh config to server.
    copy:
      src: sshd_config.template
      dest: /etc/ssh/sshd_config
